server:
  port: ${PORT:5001}

spring:
  datasource:
#    url: jdbc:mysql://hsureadme-db.c6g1mb0aat8t.ap-northeast-2.rds.amazonaws.com:3306/hsu_readme
#    username: admin
#    password: Lifesibal22

#    local: h2
#    url: jdbc:h2:tcp://localhost/~/readme
#    username: jgeun
#    password: 1234
#    driver-class-name: org.h2.Driver

    local: mysql
    url: jdbc:mysql://localhost:3306/HsuReadMe?serverTimezone=Asia/Seoul
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace